import { BankSoalButir } from '../src/types';

export const INITIAL_BUTIR_SOAL_LIST: BankSoalButir[] = [
  // ==========================================
  // BUTIR SOAL SD (SEKOLAH DASAR)
  // ==========================================
  {
    id: 'soal-sd-001',
    mapel_id: 'mapel-sd-mat-4',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 4',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 4.1',
    tujuan_pembelajaran: 'TP 4.1: Menentukan kelipatan persekutuan terkecil (KPK) dan FPB dari dua bilangan cacah dalam konteks kehidupan sehari-hari.',
    lingkup_materi: 'Bilangan Cacah & Teori Bilangan',
    indikator_soal: 'Disajikan permasalahan kontekstual jadwal kegiatan berkala, peserta didik dapat menentukan waktu pertemuan bersama menggunakan konsep KPK.',
    capaian_pembelajaran: 'Menyelesaikan masalah yang berkaitan dengan KPK dan FPB',
    stimulus_konten: 'Dua orang siswa SD Bintang, Rizky dan Budi, mengikuti ekstrakurikuler renang di kolam yang sama. Rizky berlatih renang setiap 4 hari sekali, sedangkan Budi berlatih renang setiap 6 hari sekali. Pada tanggal 2 Mei 2026, mereka berdua berlatih renang bersama-sama untuk pertama kalinya.',
    pertanyaan_teks: 'Pada tanggal berapakah Rizky dan Budi akan berlatih renang bersama-sama untuk yang kedua kalinya?',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '10 Mei 2026' },
      { id: 'opt-2', label: 'B', teks: '12 Mei 2026' },
      { id: 'opt-3', label: 'C', teks: '14 Mei 2026' },
      { id: 'opt-4', label: 'D', teks: '16 Mei 2026' },
    ],
    kunci_jawaban_terenkripsi: 'opt-3', // KPK(4,6) = 12 hari. 2 Mei + 12 hari = 14 Mei 2026
    bobot_nilai: 2.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-1',
    nama_penulis: 'Siti Rahmawati, S.Pd.SD',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-002',
    mapel_id: 'mapel-sd-mat-4',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 4',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L1',
    kode_tp: 'TP 4.2',
    tujuan_pembelajaran: 'TP 4.2: Mengubah dan membandingkan berbagai bentuk pecahan biasa, pecahan campuran, desimal, dan persentase.',
    lingkup_materi: 'Pecahan & Desimal',
    indikator_soal: 'Peserta didik dapat mengubah pecahan biasa menjadi bentuk desimal dan persentase yang senilai.',
    capaian_pembelajaran: 'Menghubungkan pecahan desimal dan persentase',
    stimulus_konten: 'Ibu membeli pita sepanjang $\\frac{3}{4}\\text{ meter}$ untuk menghias kado ulang tahun adik.',
    pertanyaan_teks: 'Bentuk desimal dan bentuk persen yang senilai dengan pecahan $\\frac{3}{4}$ berturut-turut adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '$0{,}34$ dan $34\\%$' },
      { id: 'opt-2', label: 'B', teks: '$0{,}75$ dan $75\\%$' },
      { id: 'opt-3', label: 'C', teks: '$0{,}43$ dan $43\\%$' },
      { id: 'opt-4', label: 'D', teks: '$0{,}25$ dan $25\\%$' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2',
    bobot_nilai: 2.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-1',
    nama_penulis: 'Siti Rahmawati, S.Pd.SD',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-003',
    mapel_id: 'mapel-sd-ipas-4',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 4',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L1',
    kode_tp: 'TP 4.1',
    tujuan_pembelajaran: 'TP 4.1: Mengidentifikasi bagian-bagian tubuh tumbuhan (akar, batang, daun, bunga) dan memahami proses fotosintesis.',
    lingkup_materi: 'Bagian Tubuh Tumbuhan & Fotosintesis',
    indikator_soal: 'Peserta didik dapat mengidentifikasi zat-zat yang diperlukan tumbuhan untuk melakukan proses fotosintesis.',
    capaian_pembelajaran: 'Menganalisis kebutuhan tumbuhan dalam fotosintesis',
    stimulus_konten: 'Tumbuhan hijau merupakan produsen utama di bumi yang mampu memasak makanannya sendiri melalui proses fotosintesis di dalam klorofil daun.',
    pertanyaan_teks: 'Komponen yang mutlak diperlukan oleh tumbuhan hijau untuk melangsungkan proses fotosintesis adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Oksigen, air, dan tanah berpasir' },
      { id: 'opt-2', label: 'B', teks: 'Karbon dioksida, air, cahaya matahari, dan klorofil' },
      { id: 'opt-3', label: 'C', teks: 'Karbon monoksida, pupuk kimia, dan angin kencang' },
      { id: 'opt-4', label: 'D', teks: 'Glukosa, oksigen, dan suhu beku' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2',
    bobot_nilai: 2.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-2',
    nama_penulis: 'Agus Salim, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-004',
    mapel_id: 'mapel-sd-ipas-4',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 4',
    jenis_soal: 'PG_KOMPLEKS',
    level_kognitif: 'L2',
    kode_tp: 'TP 4.2',
    tujuan_pembelajaran: 'TP 4.2: Menganalisis wujud zat (padat, cair, gas) dan perubahan wujud zat dalam kehidupan sehari-hari.',
    lingkup_materi: 'Materi & Perubahan Wujud Zat',
    indikator_soal: 'Peserta didik dapat menentukan pasangan peristiwa sehari-hari yang termasuk perubahan wujud melepaskan kalor atau menyerap kalor.',
    capaian_pembelajaran: 'Menganalisis perubahan wujud zat',
    stimulus_konten: 'Perhatikan beberapa peristiwa perubahan wujud zat berikut:\n1. Es batu yang dibiarkan di udara terbuka berubah menjadi air.\n2. Titik-titik air yang terbentuk di dinding luar gelas berisi air dingin.\n3. Kapur barus di dalam lemari yang lama-kelamaan habis menjadi gas wangi.\n4. Air yang mendidih berubah menjadi uap air.',
    pertanyaan_teks: 'Pilihlah semua pernyataan yang BENAR mengenai perubahan wujud zat di atas! (Jawaban dapat lebih dari satu)',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Peristiwa 1 (es mencair) merupakan peristiwa yang menyerap kalor dari lingkungan.' },
      { id: 'opt-2', label: 'B', teks: 'Peristiwa 2 merupakan peristiwa mengembun (gas menjadi cair).' },
      { id: 'opt-3', label: 'C', teks: 'Peristiwa 3 merupakan peristiwa menyublim (padat langsung menjadi gas).' },
      { id: 'opt-4', label: 'D', teks: 'Peristiwa 4 merupakan peristiwa membeku.' },
    ],
    kunci_jawaban_terenkripsi: ['opt-1', 'opt-2', 'opt-3'],
    bobot_nilai: 3.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-2',
    nama_penulis: 'Agus Salim, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-005',
    mapel_id: 'mapel-sd-ipas-5',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 5',
    jenis_soal: 'ESAI_URAIAN',
    level_kognitif: 'L3',
    kode_tp: 'TP 5.1',
    tujuan_pembelajaran: 'TP 5.1: Menganalisis hubungan antar makhluk hidup pada rantai makanan dan jaring-jaring makanan dalam ekosistem alam.',
    lingkup_materi: 'Ekosistem & Keseimbangan Lingkungan',
    indikator_soal: 'Disajikan skema rantai makanan sawah, peserta didik dapat memprediksi dampak kepunahan populasi tertentu terhadap keseimbangan ekosistem.',
    capaian_pembelajaran: 'Menganalisis jaring-jaring makanan pada ekosistem',
    stimulus_konten: 'Pada sebuah ekosistem sawah terdapat rantai makanan: Padi -> Belalang -> Katak -> Ular Sawah -> Burung Elang -> Pengurai. Karena dianggap berbahaya, para petani memburu dan membasmi seluruh ular sawah yang ada di kawasan persawahan tersebut.',
    pertanyaan_teks: 'Jelaskan dampak yang akan terjadi terhadap populasi katak dan populasi burung elang akibat perburuan ular sawah tersebut, serta bagaimana pengaruhnya terhadap produksi tanaman padi petani!',
    opsi_jawaban_json: [],
    kunci_jawaban_terenkripsi: 'Populasi katak bertambah banyak, burung elang berkurang makanannya, padi berpotensi aman dari belalang.',
    bobot_nilai: 8.0,
    rubrik_penilaian_esai: 'Skor 8: Menjelaskan dengan tepat bahwa populasi katak akan meningkat pesat karena tidak ada predator pemangsanya (skor 3). Menjelaskan populasi elang akan menurun/mencari mangsa lain karena sumber makanan utama berkurang (skor 3). Menjelaskan pengaruh terhadap keseimbangan belalang dan tanaman padi secara logis (skor 2).',
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-2',
    nama_penulis: 'Agus Salim, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-006',
    mapel_id: 'mapel-sd-bin-4',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 4',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 4.1',
    tujuan_pembelajaran: 'TP 4.1: Menemukan gagasan pokok dan gagasan pendukung dalam teks paragraf naratif dan informatif.',
    lingkup_materi: 'Ide Pokok Paragraf',
    indikator_soal: 'Peserta didik dapat menentukan gagasan utama paragraf informatif.',
    capaian_pembelajaran: 'Menentukan ide pokok teks informatif',
    stimulus_konten: 'Bambu merupakan salah satu tanaman serbaguna yang banyak tumbuh di Indonesia. Batang bambu yang lentur dan kuat dapat digunakan sebagai bahan bangunan rumah tradisional, tiang bendera, maupun pagar pekarangan. Selain itu, rebung atau tunas bambu muda juga sering diolah masyarakat menjadi aneka hidangan lezat berprotein.',
    pertanyaan_teks: 'Gagasan pokok dari paragraf di atas adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Bambu hanya tumbuh di daerah pedesaan Indonesia.' },
      { id: 'opt-2', label: 'B', teks: 'Manfaat dan kegunaan tanaman bambu yang serbaguna.' },
      { id: 'opt-3', label: 'C', teks: 'Cara mengolah tunas bambu muda menjadi makanan.' },
      { id: 'opt-4', label: 'D', teks: 'Kelemahan tanaman bambu untuk bahan bangunan.' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2',
    bobot_nilai: 2.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-1',
    nama_penulis: 'Siti Rahmawati, S.Pd.SD',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-007',
    mapel_id: 'mapel-sd-bin-1',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 1',
    fase_kurikulum: 'Fase A (Kurikulum Merdeka)',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L1',
    kode_tp: 'TP 1.1',
    tujuan_pembelajaran: 'TP 1.1: Mengenal dan melafalkan bunyi huruf vokal dan konsonan serta merangkai suku kata menjadi kata bermakna.',
    lingkup_materi: 'Bunyi Huruf & Suku Kata',
    indikator_soal: 'Disajikan gambar benda sehari-hari, peserta didik dapat melengkapi suku kata awal kata benda tersebut dengan tepat.',
    capaian_pembelajaran: 'Mengenal huruf dan membaca suku kata',
    stimulus_konten: 'Perhatikan gambar benda yang biasa dipakai untuk menulis: [ B _ _ U ]. Kata yang tepat adalah BUKU.',
    pertanyaan_teks: 'Suku kata yang tepat untuk melengkapi kata **BU - ...** agar menjadi nama benda tempat membaca adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'KA' },
      { id: 'opt-2', label: 'B', teks: 'KU' },
      { id: 'opt-3', label: 'C', teks: 'KI' },
      { id: 'opt-4', label: 'D', teks: 'KO' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2',
    bobot_nilai: 2.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-1',
    nama_penulis: 'Siti Rahmawati, S.Pd.SD',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-008',
    mapel_id: 'mapel-sd-mat-1',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 1',
    fase_kurikulum: 'Fase A (Kurikulum Merdeka)',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L1',
    kode_tp: 'TP 1.2',
    tujuan_pembelajaran: 'TP 1.2: Melakukan operasi penjumlahan dan pengurangan bilangan cacah sampai dengan 10.',
    lingkup_materi: 'Penjumlahan & Pengurangan Dasar',
    indikator_soal: 'Peserta didik dapat menyelesaikan soal cerita sederhana penjumlahan bilangan cacah.',
    capaian_pembelajaran: 'Menyelesaikan penjumlahan bilangan cacah sampai 10',
    stimulus_konten: 'Ani memiliki 4 buah apel merah di keranjang. Ibu memberi Ani 3 buah apel lagi.',
    pertanyaan_teks: 'Berapakah jumlah seluruh apel yang dimiliki Ani sekarang? ($4 + 3 = \\dots$)',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '5 apel' },
      { id: 'opt-2', label: 'B', teks: '6 apel' },
      { id: 'opt-3', label: 'C', teks: '7 apel' },
      { id: 'opt-4', label: 'D', teks: '8 apel' },
    ],
    kunci_jawaban_terenkripsi: 'opt-3',
    bobot_nilai: 2.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-1',
    nama_penulis: 'Siti Rahmawati, S.Pd.SD',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-009',
    mapel_id: 'mapel-sd-mat-6',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 6',
    fase_kurikulum: 'Fase C (Kurikulum Merdeka)',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 6.1',
    tujuan_pembelajaran: 'TP 6.1: Menjelaskan bilangan bulat negatif serta operasi penjumlahan dan pengurangannya dalam garis bilangan.',
    lingkup_materi: 'Bilangan Bulat Negatif & Garis Bilangan',
    indikator_soal: 'Peserta didik dapat menyelesaikan soal cerita perubahan suhu menggunakan bilangan bulat negatif.',
    capaian_pembelajaran: 'Mengoperasikan bilangan bulat dalam kehidupan sehari-hari',
    stimulus_konten: 'Suhu di dalam lemari pendingin (freezer) mula-mula adalah $-4^\\circ\\text{C}$. Ketika aliran listrik padam selama 2 jam, suhu di dalam freezer naik sebesar $7^\\circ\\text{C}$.',
    pertanyaan_teks: 'Berapakah suhu di dalam freezer tersebut sekarang?',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '$-11^\\circ\\text{C}$' },
      { id: 'opt-2', label: 'B', teks: '$-3^\\circ\\text{C}$' },
      { id: 'opt-3', label: 'C', teks: '$3^\\circ\\text{C}$' },
      { id: 'opt-4', label: 'D', teks: '$11^\\circ\\text{C}$' },
    ],
    kunci_jawaban_terenkripsi: 'opt-3', // -4 + 7 = 3
    bobot_nilai: 3.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-2',
    nama_penulis: 'Agus Salim, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-sd-010',
    mapel_id: 'mapel-sd-ipas-6',
    jenjang_sekolah: 'SD',
    tingkat_kelas: 'Kelas 6',
    fase_kurikulum: 'Fase C (Kurikulum Merdeka)',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 6.2',
    tujuan_pembelajaran: 'TP 6.2: Mengidentifikasi komponen listrik serta membedakan rangkaian listrik seri dan paralel.',
    lingkup_materi: 'Kelistrikan & Rangkaian Seri Paralel',
    indikator_soal: 'Peserta didik dapat menentukan keuntungan rangkaian listrik paralel pada instalasi listrik rumah tangga.',
    capaian_pembelajaran: 'Menganalisis rangkaian listrik seri dan paralel',
    stimulus_konten: 'Instalasi lampu-lampu di rumah umumnya dirangkai secara paralel, bukan secara seri.',
    pertanyaan_teks: 'Alasan utama penggunaan rangkaian paralel untuk lampu di rumah adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Hanya membutuhkan satu buah kabel saja' },
      { id: 'opt-2', label: 'B', teks: 'Jika satu lampu padam, lampu yang lain tetap dapat menyala' },
      { id: 'opt-3', label: 'C', teks: 'Arus listrik yang mengalir menjadi nol' },
      { id: 'opt-4', label: 'D', teks: 'Lampu menjadi lebih redup sehingga hemat energi' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2',
    bobot_nilai: 3.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-sd-2',
    nama_penulis: 'Agus Salim, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ==========================================
  // BUTIR SOAL SMP (SEKOLAH MENENGAH PERTAMA)
  // ==========================================
  {
    id: 'soal-smp-001',
    mapel_id: 'mapel-smp-ipa-7',
    jenjang_sekolah: 'SMP',
    tingkat_kelas: 'Kelas 7',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 7.1',
    tujuan_pembelajaran: 'TP 7.1: Menganalisis konsep suhu, pemuaian zat, dan perpindahan kalor dalam fenomena alam serta teknologi pendingin.',
    lingkup_materi: 'Suhu, Pemuaian & Kalor',
    indikator_soal: 'Disajikan data konversi termometer Celsius ke Reamur atau Fahrenheit, peserta didik dapat menghitung skala suhu dengan tepat.',
    capaian_pembelajaran: 'Mengonversi skala termometer suhu zat',
    stimulus_konten: 'Pada sebuah praktikum fisika di laboratorium IPA, seorang siswa mengukur suhu air mendidih menggunakan termometer Celsius dan terbaca $80^\\circ\\text{C}$. Hubungan antara skala Celsius dan skala Reamur dinyatakan dengan perbandingan $C : R = 5 : 4$.',
    pertanyaan_teks: 'Jika air tersebut diukur suhunya menggunakan termometer Reamur, maka angka yang ditunjukkan adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '$48^\\circ\\text{R}$' },
      { id: 'opt-2', label: 'B', teks: '$64^\\circ\\text{R}$' },
      { id: 'opt-3', label: 'C', teks: '$72^\\circ\\text{R}$' },
      { id: 'opt-4', label: 'D', teks: '$100^\\circ\\text{R}$' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2', // (4/5) * 80 = 64
    bobot_nilai: 2.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-smp-1',
    nama_penulis: 'Rendra Hendrawan, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-smp-002',
    mapel_id: 'mapel-smp-ipa-7',
    jenjang_sekolah: 'SMP',
    tingkat_kelas: 'Kelas 7',
    jenis_soal: 'PG_KOMPLEKS',
    level_kognitif: 'L2',
    kode_tp: 'TP 7.2',
    tujuan_pembelajaran: 'TP 7.2: Mengidentifikasi sistem organisasi kehidupan mulai dari tingkat sel, jaringan, organ, hingga sistem organ manusia.',
    lingkup_materi: 'Organisasi Kehidupan & Sel',
    indikator_soal: 'Peserta didik dapat membedakan organel yang hanya dimiliki oleh sel tumbuhan atau sel hewan.',
    capaian_pembelajaran: 'Menganalisis perbedaan sel tumbuhan dan sel hewan',
    stimulus_konten: 'Sel merupakan unit struktural dan fungsional terkecil dari makhluk hidup. Meskipun memiliki struktur dasar serupa, sel tumbuhan memiliki organel spesifik yang tidak dimiliki oleh sel hewan untuk menunjang cara hidupnya.',
    pertanyaan_teks: 'Organel sel berikut manakah yang HANYA terdapat pada sel tumbuhan dan TIDAK ditemukan pada sel hewan normal? (Pilihan dapat lebih dari satu)',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Dinding sel yang tersusun atas selulosa' },
      { id: 'opt-2', label: 'B', teks: 'Kloroplas (plastida penghasil klorofil)' },
      { id: 'opt-3', label: 'C', teks: 'Vakuola sentral berukuran besar' },
      { id: 'opt-4', label: 'D', teks: 'Mitokondria pembentuk energi ATP' },
    ],
    kunci_jawaban_terenkripsi: ['opt-1', 'opt-2', 'opt-3'],
    bobot_nilai: 3.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-smp-1',
    nama_penulis: 'Rendra Hendrawan, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-smp-003',
    mapel_id: 'mapel-smp-mat-8',
    jenjang_sekolah: 'SMP',
    tingkat_kelas: 'Kelas 8',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 8.2',
    tujuan_pembelajaran: 'TP 8.2: Membuktikan dan mengaplikasikan Teorema Pythagoras untuk menentukan jarak dan sisi miring segitiga siku-siku.',
    lingkup_materi: 'Teorema Pythagoras',
    indikator_soal: 'Disajikan permasalahan tiang kabel listrik atau tangga bersandar, siswa dapat menghitung panjang sisi menggunakan Teorema Pythagoras.',
    capaian_pembelajaran: 'Menerapkan Teorema Pythagoras dalam pemecahan masalah',
    stimulus_konten: 'Sebuah tangga yang panjangnya $10\\text{ meter}$ disandarkan pada tembok gedung sekolah. Jika jarak ujung bawah tangga ke dinding tembok adalah $6\\text{ meter}$, anggap tanah dan dinding tembok tegak lurus ($90^\\circ$).',
    pertanyaan_teks: 'Tinggi ujung atas tangga dari permukaan tanah adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '$7\\text{ meter}$' },
      { id: 'opt-2', label: 'B', teks: '$8\\text{ meter}$' },
      { id: 'opt-3', label: 'C', teks: '$9\\text{ meter}$' },
      { id: 'opt-4', label: 'D', teks: '$12\\text{ meter}$' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2', // sqrt(10^2 - 6^2) = sqrt(64) = 8
    bobot_nilai: 2.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-smp-2',
    nama_penulis: 'Dewi Anggraeni, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-smp-004',
    mapel_id: 'mapel-smp-mat-8',
    jenjang_sekolah: 'SMP',
    tingkat_kelas: 'Kelas 8',
    jenis_soal: 'ISIAN_SINGKAT',
    level_kognitif: 'L2',
    kode_tp: 'TP 8.3',
    tujuan_pembelajaran: 'TP 8.3: Menyelesaikan sistem persamaan linear dua variabel (SPLDV) menggunakan metode grafik, substitusi, dan eliminasi.',
    lingkup_materi: 'Sistem Persamaan Linear Dua Variabel (SPLDV)',
    indikator_soal: 'Peserta didik dapat menyelesaikan nilai x dan y dari sistem persamaan dua variabel.',
    capaian_pembelajaran: 'Menyelesaikan SPLDV',
    stimulus_konten: 'Diberikan sistem persamaan linear dua variabel:\n$$\\begin{cases} 2x + y = 11 \\\\ x - y = 1 \\end{cases}$$',
    pertanyaan_teks: 'Berapakah nilai dari perkalian $x \\times y$? Tuliskan hanya angka jawabannya.',
    opsi_jawaban_json: [],
    kunci_jawaban_terenkripsi: '12', // 3x = 12 -> x=4, y=3 -> 4*3 = 12
    bobot_nilai: 3.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-smp-2',
    nama_penulis: 'Dewi Anggraeni, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-smp-005',
    mapel_id: 'mapel-smp-infor-7',
    jenjang_sekolah: 'SMP',
    tingkat_kelas: 'Kelas 7',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 7.1',
    tujuan_pembelajaran: 'TP 7.1: Menerapkan 4 pilar berpikir komputasional (dekomposisi, pengenalan pola, abstraksi, algoritma) untuk memecahkan persoalan komputasi.',
    lingkup_materi: 'Berpikir Komputasional (BK)',
    indikator_soal: 'Peserta didik dapat mengidentifikasi penerapan pilar dekomposisi atau abstraksi dalam kehidupan nyata.',
    capaian_pembelajaran: 'Menerapkan pilar berpikir komputasional',
    stimulus_konten: 'Ketika seorang koki hendak memasak hidangan nasi tumpeng komplit untuk acara syukuran, koki tersebut memecah proyek besar tersebut menjadi beberapa sub-tugas kecil: memasak nasi kuning, membuat ayam goreng, menumis tempe orek, dan menata hiasan sayuran.',
    pertanyaan_teks: 'Aktivitas memecah masalah yang kompleks menjadi bagian-bagian yang lebih kecil dan lebih mudah dikelola mencerminkan pilar berpikir komputasional, yaitu...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Dekomposisi (Decomposition)' },
      { id: 'opt-2', label: 'B', teks: 'Pengenalan Pola (Pattern Recognition)' },
      { id: 'opt-3', label: 'C', teks: 'Abstraksi (Abstraction)' },
      { id: 'opt-4', label: 'D', teks: 'Debugging' },
    ],
    kunci_jawaban_terenkripsi: 'opt-1',
    bobot_nilai: 2.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-smp-3',
    nama_penulis: 'Fajar Nugroho, S.Kom.',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-smp-006',
    mapel_id: 'mapel-smp-ipa-8',
    jenjang_sekolah: 'SMP',
    tingkat_kelas: 'Kelas 8',
    jenis_soal: 'ESAI_URAIAN',
    level_kognitif: 'L3',
    kode_tp: 'TP 8.1',
    tujuan_pembelajaran: 'TP 8.1: Menganalisis sistem gerak pada manusia (tulang, sendi, otot) dan penerapannya pada prinsip kerja pesawat sederhana.',
    lingkup_materi: 'Sistem Gerak & Pesawat Sederhana',
    indikator_soal: 'Peserta didik dapat mengidentifikasi jenis tuas/pengungkit pada gerakan tubuh manusia saat mengangkat beban.',
    capaian_pembelajaran: 'Menganalisis prinsip pesawat sederhana pada otot manusia',
    stimulus_konten: 'Ketika seseorang mengangkat barbel menggunakan tangan dengan menekuk siku ke atas, otot bisep berkontraksi dan otot trisep berelaksasi. Sendi siku berperan sebagai titik tumpu, otot bisep memberikan gaya kuasa, dan barbel di telapak tangan bertindak sebagai beban.',
    pertanyaan_teks: 'Berdasarkan susunan titik tumpu, titik beban, dan titik kuasa, jenis pengungkit (tuas) golongan ke berapakah prinsip kerja lengan bawah tersebut? Jelaskan alasannya secara ilmiah!',
    opsi_jawaban_json: [],
    kunci_jawaban_terenkripsi: 'Pengungkit jenis ketiga (Tuas Golongan 3), karena posisi titik kuasa (otot bisep) berada di antara titik tumpu (sendi siku) dan titik beban (tangan memegang barbel).',
    bobot_nilai: 8.0,
    rubrik_penilaian_esai: 'Menyebutkan dengan tepat pengungkit golongan 3 (skor 3). Menjelaskan posisi letak titik kuasa di tengah antara titik tumpu dan titik beban (skor 3). Mengaitkan fungsi kontraksi otot bisep dengan gaya kuasa (skor 2).',
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-smp-1',
    nama_penulis: 'Rendra Hendrawan, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 1).toISOString(),
    updated_at: new Date().toISOString(),
  },

  // ==========================================
  // BUTIR SOAL SMA (SEKOLAH MENENGAH ATAS)
  // ==========================================
  {
    id: 'soal-101',
    mapel_id: 'mapel-1',
    jenjang_sekolah: 'SMA',
    tingkat_kelas: 'Kelas 10',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L1',
    kode_tp: 'TP 10.1',
    tujuan_pembelajaran: 'TP 10.1: Menyelesaikan permasalahan sistem persamaan dan karakteristik titik balik fungsi kuadrat.',
    lingkup_materi: 'Fungsi Kuadrat & Aljabar',
    indikator_soal: 'Peserta didik dapat menentukan koordinat titik balik minimum fungsi kuadrat.',
    capaian_pembelajaran: 'Menyelesaikan permasalahan sistem persamaan dan fungsi kuadrat dasar',
    stimulus_konten: 'Diberikan fungsi kuadrat standar $f(x) = ax^2 + bx + c$ dengan $a \\neq 0$. Titik puncak kurva parabola ditentukan melalui koordinat $\\left(-\\frac{b}{2a}, -\\frac{D}{4a}\\right)$ di mana diskriminan $D = b^2 - 4ac$.',
    pertanyaan_teks: 'Jika sebuah fungsi kuadrat didefinisikan sebagai $f(x) = 2x^2 - 8x + 6$, maka koordinat titik balik minimum grafik fungsi tersebut adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '$(2, -2)$' },
      { id: 'opt-2', label: 'B', teks: '$(2, 2)$' },
      { id: 'opt-3', label: 'C', teks: '$(-2, -2)$' },
      { id: 'opt-4', label: 'D', teks: '$(4, -2)$' },
      { id: 'opt-5', label: 'E', teks: '$(1, 0)$' },
    ],
    kunci_jawaban_terenkripsi: 'opt-1', // A
    bobot_nilai: 2.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-1',
    nama_penulis: 'Dra. Sri Wahyuni, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 4).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-102',
    mapel_id: 'mapel-1',
    jenjang_sekolah: 'SMA',
    tingkat_kelas: 'Kelas 10',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L2',
    kode_tp: 'TP 10.2',
    tujuan_pembelajaran: 'TP 10.2: Menerapkan konsep barisan dan deret geometri dalam perhitungan bunga majemuk finansial.',
    lingkup_materi: 'Barisan dan Deret Geometri',
    indikator_soal: 'Peserta didik dapat menghitung akumulasi nilai investasi dengan suku bunga majemuk berkala.',
    capaian_pembelajaran: 'Menerapkan konsep barisan dan deret geometri dalam perhitungan finansial',
    stimulus_konten: 'Seorang pengusaha UMKM menginvestasikan modal awal sebesar Rp10.000.000 pada instrumen bagi hasil dengan pertumbuhan majemuk berkala setiap tahun sebesar $r = 10\\% = 0{,}1$. Nilai modal pada akhir tahun ke-$n$ dimodelkan dengan formula $M_n = M_0(1 + r)^n$.',
    pertanyaan_teks: 'Berdasarkan model pertumbuhan tersebut, taksiran akumulasi modal pengusaha tersebut pada akhir tahun ke-3 adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Rp12.100.000' },
      { id: 'opt-2', label: 'B', teks: 'Rp13.000.000' },
      { id: 'opt-3', label: 'C', teks: 'Rp13.310.000' },
      { id: 'opt-4', label: 'D', teks: 'Rp14.641.000' },
      { id: 'opt-5', label: 'E', teks: 'Rp15.000.000' },
    ],
    kunci_jawaban_terenkripsi: 'opt-3', // C -> 10jt * 1.331 = 13.310.000
    bobot_nilai: 2.5,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-1',
    nama_penulis: 'Dra. Sri Wahyuni, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-103',
    mapel_id: 'mapel-1',
    jenjang_sekolah: 'SMA',
    tingkat_kelas: 'Kelas 10',
    jenis_soal: 'PG_KOMPLEKS',
    level_kognitif: 'L3',
    kode_tp: 'TP 10.3',
    tujuan_pembelajaran: 'TP 10.3: Menganalisis karakteristik limit dan kekontinuan fungsi aljabar.',
    lingkup_materi: 'Kalkulus & Limit Fungsi',
    indikator_soal: 'Peserta didik dapat menganalisis nilai limit fungsi pecahan aljabar.',
    capaian_pembelajaran: 'Menganalisis karakteristik limit dan kekontinuan fungsi rasional (HOTS)',
    stimulus_konten: 'Perhatikan fungsi pecahan aljabar $g(x) = \\frac{x^2 - 9}{x - 3}$. Fungsi ini memiliki domain seluruh bilangan riil kecuali $x = 3$ karena pembagian dengan nol tidak terdefinisi secara langsung.',
    pertanyaan_teks: 'Pilihlah semua pernyataan matematika yang bernilai BENAR terkait fungsi $g(x)$ di atas! (Pilihan dapat lebih dari satu)',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: 'Nilai limit $\\lim_{x \\to 3} g(x) = 6$.' },
      { id: 'opt-2', label: 'B', teks: 'Grafik fungsi $g(x)$ berbentuk garis lurus dengan sebuah titik berlubang (removable discontinuity) pada koordinat $(3, 6)$.' },
      { id: 'opt-3', label: 'C', teks: 'Nilai fungsi $g(3)$ bernilai tepat 6.' },
      { id: 'opt-4', label: 'D', teks: 'Turunan pertama dari fungsi penyederhanaannya untuk $x \\neq 3$ adalah $g\'(x) = 1$.' },
    ],
    kunci_jawaban_terenkripsi: ['opt-1', 'opt-2', 'opt-4'],
    bobot_nilai: 4.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-1',
    nama_penulis: 'Dra. Sri Wahyuni, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-105',
    mapel_id: 'mapel-1',
    jenjang_sekolah: 'SMA',
    tingkat_kelas: 'Kelas 10',
    jenis_soal: 'ESAI_URAIAN',
    level_kognitif: 'L3',
    kode_tp: 'TP 10.1',
    tujuan_pembelajaran: 'TP 10.1: Menyelesaikan permasalahan sistem persamaan dan karakteristik titik balik fungsi kuadrat.',
    lingkup_materi: 'Fungsi Kuadrat & Aljabar',
    indikator_soal: 'Peserta didik dapat merumuskan model fungsi luas dan menentukan nilai maksimum kandang.',
    capaian_pembelajaran: 'Memodelkan permasalahan optimasi luas lahan menggunakan turunan fungsi kuadrat',
    stimulus_konten: 'Pak Hendra memiliki kawat pembatas sepanjang $120\\text{ meter}$. Kawat tersebut akan digunakan untuk memagari kandang ayam berbentuk persegi panjang di mana salah satu sisinya menempel pada dinding tembok batu bata yang kokoh (sehingga sisi dinding tidak membutuhkan kawat).',
    pertanyaan_teks: 'Tentukan model matematika fungsi luas $L(x)$, ukuran panjang dan lebar kandang agar diperoleh luas maksimum, serta hitung luas maksimum area kandang tersebut!',
    opsi_jawaban_json: [],
    kunci_jawaban_terenkripsi: 'Lebar x = 30 m, Panjang y = 60 m, Luas Maksimum = 1800 m²',
    bobot_nilai: 8.0,
    rubrik_penilaian_esai: 'Skor 8: Model fungsi $L(x) = x(120 - 2x) = 120x - 2x^2$ benar (skor 2). Penentuan titik stasioner $L\'(x) = 120 - 4x = 0 \\implies x = 30$ benar (skor 2). Perhitungan dimensi panjang $y = 60\\text{ m}$ benar (skor 2). Perhitungan luas maksimum $1800\\text{ m}^2$ disertai satuan benar (skor 2).',
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-1',
    nama_penulis: 'Dra. Sri Wahyuni, M.Pd.',
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'soal-201',
    mapel_id: 'mapel-2',
    jenjang_sekolah: 'SMA',
    tingkat_kelas: 'Kelas 11',
    jenis_soal: 'PILIHAN_GANDA',
    level_kognitif: 'L1',
    kode_tp: 'TP 11.1',
    tujuan_pembelajaran: 'TP 11.1: Menerapkan hukum kedua Newton tentang gerak lurus berubah beraturan dan dinamika partikel.',
    lingkup_materi: 'Hukum Gerak Newton',
    indikator_soal: 'Peserta didik dapat menghitung percepatan balok berdasarkan gaya horizontal dan massa.',
    capaian_pembelajaran: 'Memahami hukum kedua Newton tentang gerak lurus berubah beraturan',
    stimulus_konten: 'Hukum II Newton menyatakan bahwa percepatan sebuah benda berbanding lurus dengan gaya total yang bekerja dan berbanding terbalik dengan massanya: $\\Sigma F = m \\cdot a$.',
    pertanyaan_teks: 'Sebuah balok bermassa $4\\text{ kg}$ berada di atas lantai licin tanpa gesekan. Jika balok ditarik dengan gaya konstan sebesar $12\\text{ N}$ searah sumbu horizontal, maka percepatan yang dialami balok adalah...',
    opsi_jawaban_json: [
      { id: 'opt-1', label: 'A', teks: '$1{,}5\\text{ m/s}^2$' },
      { id: 'opt-2', label: 'B', teks: '$3{,}0\\text{ m/s}^2$' },
      { id: 'opt-3', label: 'C', teks: '$4{,}0\\text{ m/s}^2$' },
      { id: 'opt-4', label: 'D', teks: '$8{,}0\\text{ m/s}^2$' },
      { id: 'opt-5', label: 'E', teks: '$48{,}0\\text{ m/s}^2$' },
    ],
    kunci_jawaban_terenkripsi: 'opt-2', // B -> 12 / 4 = 3
    bobot_nilai: 2.0,
    status_validasi: 'TERVALIDASI',
    penulis_guru_id: 'guru-3',
    nama_penulis: 'Ahmad Fauzi, M.T.',
    created_at: new Date(Date.now() - 86400000 * 3).toISOString(),
    updated_at: new Date().toISOString(),
  },
];
